# login:
#    path: /login
#    methods:
#       GET
#       POST
#    controller: App\Controller\SecurityController::login

# logout:
#    path: /logout
#    controller: App\Controller\SecurityController::logout

# homePage:
#    path: /
#    methods: GET
#    controller: App\Controller\ResultController::get_result

# resultGet:
#    path: /result
#    methods: GET
#    controller: App\Controller\ResultController::get_result

# resultShow:
#    path: result/{id}
#    methods: GET
#    controller: App\Controller\ResultController::show_result

# cardGet:
#    path: card
#    methods: GET
#    controller: App\Controller\TokenNumberController::get_card

# cardUpdate:
#    path: card
#    methods: POST
#    controller: App\Controller\TokenNumberController::update_card

